### ISSUE TITLE
如何搭建dubbo-admin管理平台

### ISSUE THREAD

**Issue by 00jiajia** [apache/incubator-dubbo-ops#56]
不好意思，对于一个初学者，看了你的readme, 还有有点懵，这个dubbo-admin可以直接部署到tomcate下面直接访问？请大声给与提点，谢谢

**Comment by BlackHe** [comment]
不用了，现在已经是spring boot版本了。下载下来。进去代码目录，执行 mvn clean package命令，再进去dubbo admin 的target 下，直接java -jar运行起来就可以了。 1124681011 邮箱：1124681011@qq.com 签名由 网易邮箱大师 定制 在2018年07月01日 15:28，00jiajia 写道： 不好意思，对于一个初学者，看了你的readme, 还有有点懵，这个dubbo-admin可以直接部署到tomcate下面直接访问？请大声给与提点，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liangzai-cool** [comment]
能不能把文档更新一下啊，搞了两次才搞好，真坑

**Comment by GaraYing** [comment]
java -jar运行springboot版本之后，输入root/guest一直登陆不进去，这是什么原因？

**Comment by nzomkxia** [comment]
the README has been updated

**Comment by zhuSilence** [comment]
请问用 redis 作为注册中心，直接将
#dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.registry.address=redis://127.0.0.1:6379
就可以了吗？好像启动不了，是还需要配置其他的吗

**Comment by zhuSilence** [comment]
> 请问用 redis 作为注册中心，直接将
> #dubbo.registry.address=zookeeper://127.0.0.1:2181
> dubbo.registry.address=redis://127.0.0.1:6379
> 就可以了吗？好像启动不了，是还需要配置其他的吗

已解决。

**Comment by changelzj** [comment]
telnet 就没调通过。。。
